### ISSUE TITLE
WhiteBox Version 2

### ISSUE THREAD

**Issue by datawrestler** [DataScienceSquad/model-describer#24]
@danielbyler @Venkat-del @shrupanda can we use GitHub projects to organize our development path for version 2? I created the project so all you need to do is check out the projects tab in Github. Drag issues that you feel are viable options for a big release of version 2 onto the whiteboard. 

Let me know if you have any questions!

-Jason

**Comment by danielbyler** [comment]
@datawrestler completed this so closing it
