### ISSUE TITLE
Repeats in error messages

### ISSUE THREAD

**Issue by danielbyler** [DataScienceSquad/model-describer#83]
There are repeats in the error messages for when errors are not consistent between the ranges. I bet it's a quick fix but it'd be great if you could look into it. 

The model tends to consistently make mistakes in the same direction when it miss-estimates density. Within the White group, the model consistently makes overestimates in the quartile range(s) 0.990-0.990, 0.990-0.990, 0.990-1.000, 1.000-1.040. Within the Red group, the model consistently makes overestimates in the quartile range(s) 0.990-1.000, 1.000-1.000, 1.000-1.000, 1.000-1.000

**Comment by datawrestler** [comment]
@danielbyler whats the bug here? When working with small datasets in small regions, this will come up frequently. This has been discussed several times in the past.
